create table if not exists public.bible_ai_verse_content (
  id bigint generated by default as identity primary key,
  translation_id bigint not null references public.bible_translations(id) on delete cascade,
  book_id bigint not null references public.bible_books(id) on delete cascade,
  chapter_number integer not null check (chapter_number > 0),
  verse_number integer not null check (verse_number > 0),
  literal_zh text not null,
  natural_zh text not null,
  source_language_notes_zh text not null,
  first_readers_zh text not null,
  model text not null,
  generated_at timestamptz not null default now(),
  unique (translation_id, book_id, chapter_number, verse_number)
);

create table if not exists public.bible_ai_chapter_studies (
  id bigint generated by default as identity primary key,
  translation_id bigint not null references public.bible_translations(id) on delete cascade,
  book_id bigint not null references public.bible_books(id) on delete cascade,
  chapter_number integer not null check (chapter_number > 0),
  overview_zh text not null,
  structure_zh text not null,
  historical_background_zh text not null,
  theological_themes_zh text not null,
  model text not null,
  generated_at timestamptz not null default now(),
  unique (translation_id, book_id, chapter_number)
);

alter table public.bible_ai_verse_content enable row level security;
alter table public.bible_ai_chapter_studies enable row level security;

drop policy if exists "Public read AI verse content" on public.bible_ai_verse_content;
create policy "Public read AI verse content"
  on public.bible_ai_verse_content for select
  using (true);

drop policy if exists "Public read AI chapter studies" on public.bible_ai_chapter_studies;
create policy "Public read AI chapter studies"
  on public.bible_ai_chapter_studies for select
  using (true);

create index if not exists bible_ai_verse_lookup
  on public.bible_ai_verse_content (translation_id, book_id, chapter_number, verse_number);

create index if not exists bible_ai_study_lookup
  on public.bible_ai_chapter_studies (translation_id, book_id, chapter_number);
